### PR TITLE
:zap: Fix USD prices

### LINKED ISSUE #155: Fix: Fix the inaccuracy of the USD equivalent
# ℹ Overview

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview
closes #155 

### 🔐 Acceptance:

- [ ] `npm run test` passes

### CODE REVIEW

File: components/BotForm.tsx [hunk 1]
```diff
@@ -387,29 +394,26 @@ export const BotForm = () => {
...
-                    setASAWarning("Warning, this ASA‘s liquidity is high");
-                    return false;
-                  }
-                } else {
+              const amountToTrade = ladderTiers * algoRate * orderAlgoDepth;
+              if (maxLiquidity) {
+                if (amountToTrade >= maxLiquidity * 0.5) {
                   setASAError(
-                    "This ASA‘s liquidity is too low on Tinyman to use this bot"
+                    "This ASA‘s liquidity is too high and risky to use this bot"
```
Comment (atrefonas) [inline components/BotForm.tsx:401]: The liquidity should say low, not high. High liquidity is a good thing

**Review by atrefonas — CHANGES_REQUESTED** [review]

File: components/BotForm.tsx (hunk 1 above)
Comment (treasurechic) [reply components/BotForm.tsx:401]: We had a conversation on this some days back;

You said: 
Less than 10% is good
Above 10% give warning
Above 50% is risky and should not trade on the bot
